   # Sudoku solver script v1.00

Script to solve a given sudoku or calculate that it has no solution 

In [1]:
import numpy as np
from math import floor

Define a sudoku to be solved in an np array:

In [2]:
sd = np.array([ [8,0,0,0,0,0,0,0,0],
                [0,0,3,6,0,0,0,0,0],
                [0,7,0,0,9,0,2,0,0],
                [0,5,0,0,0,7,0,0,0],
                [0,0,0,0,4,5,7,0,0],
                [0,0,0,1,0,0,0,3,0],
                [0,0,1,0,0,0,0,6,8],
                [0,0,8,5,0,0,0,1,0],
                [0,9,0,0,0,0,4,0,0]]) 

Below split() function segments input board based on the nine 3x3 squares:

In [3]:
#takes each 3x3 section from the board and adds all entries into a list corresponding to each 3x3 grid
#need to check box function once complete, will list of subarrays change and be dependent on original board?

#board splitting function

def split(board):
    z = 0
    subBoards = []

    for i in range(9):

        if i%3 == 0:
            z = 0
        else:
            z += 3

        sdTemp = sd[ (3*floor(i/3)):(3*floor(i/3) +3), z:(z+3) ]
        sdTemp = sdTemp.reshape(9, )

        if i == 0:
            subBoards = sdTemp
        else:
            subBoards = np.vstack((subBoards,sdTemp))
    
    return subBoards

Define box() function to check if a given number in a given already exists in the related 3x3 subgrid 

In [4]:
#need to define subgrid variable at start of each iteration of the box function so that it captures changes
#check that reshape function will not affect dependency on original board

def box(board, i, j, p):
    subBoards = split(board)
    subGrid = (3*floor(i/3) + floor(j/3))
    
    if p in subBoards[subGrid]:
        return False
    else:
        return True

Constraint check defined below. It's checking three things:
#1 For the presence of a given number in the row
#2 For the presence of a given number in the column
#3 For the presence of a given number in the 3x3 grid of the cell

In [5]:
# checking number p in cell [i, j] in board

def constraint(board, i, j, p):
    if (p not in board[i, 0:]) and (p not in board[0:, j]) and box(board, i, j, p) == True:
        return True
    else:
        return False

zspace() function defined below takes input board and stores coordinates of all zeroes of the original board in a list

In [6]:
#takes input board and generates array containing coordinates of zeros

def zspace(board):
    coord = []
    
    for i in range(9):
        for j in range(9):
            if board[i][j] == 0:
                coord.append([i, j])
    return coord
    

Backtracking solve function defined below:

In [7]:
#takes input board and generic counting variable as input 

def btrck(board):
    zsp = zspace(board)
    
    if len(zsp) == 0:
        return True
    
    for n in range(1, 10):
            
        if constraint(board, zsp[0][0], zsp[0][1], n):
            board[ (zsp[0][0], zsp[0][1]) ] = n
            
            if btrck(board):
                return True
            
            board[ (zsp[0][0], zsp[0][1]) ] = 0
    
    return False

Running full function below and outputting solution board

In [8]:
def solution(board):
    
    if btrck(board) == True:
        return print(board)
    else:
        return print("No solution")

Solution below:

In [9]:
solution(sd)

[[8 1 2 7 5 3 6 4 9]
 [9 4 3 6 8 2 1 7 5]
 [6 7 5 4 9 1 2 8 3]
 [1 5 4 2 3 7 8 9 6]
 [3 6 9 8 4 5 7 2 1]
 [2 8 7 1 6 9 5 3 4]
 [5 2 1 9 7 4 3 6 8]
 [4 3 8 5 2 6 9 1 7]
 [7 9 6 3 1 8 4 5 2]]
